# Generated by Django 4.1.7 on 2023-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ShoppingC',
            field=models.IntegerField(default=0),
        ),
    ]
