# Generated by Django 4.1.7 on 2023-08-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gaming', '0002_alter_game_shoppingc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Big',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total', models.IntegerField()),
            ],
        ),
    ]
